server:
   port: 9001
javax:
   sql:
      DataSource:
         airportDataSource:
            dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource 
            dataSource:
               url: jdbc:mysql://localhost:3306/airport-db?characterEncoding=latin1&useConfigs=maxPerformance
               user: root
               password: afsaralam15
               
               
               